default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: d8c3p6g82624jk

test:
  <<: *default
  database: d8c3p6g82624jk

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
